### ISSUE TITLE
Bug in ScaleTransform

### ISSUE THREAD

**Issue by Lucas-Steinmann** [facebookresearch/fvcore#26]
If I'm not mistaken the scale transform scales the width by the ``new_h`` parameter and the height by the ``new_w`` parameter.
Expected input is ``NxHxWxC``. (height first)
But ``size`` argument to ``interpolate`` is ``(self.new_w, self.new_h)`` (width first).
The call to ``to_float_tensor`` doesn't seem to swap spatial dimensions either.

The line I'm concerned with is the following: https://github.com/facebookresearch/fvcore/blob/ae36e95be066bfe4e95831bf11de68578ca01959/fvcore/transforms/transform.py#L421

Maybe the following makes it clearer:

```python3
>>> new_h, new_w = 480, 720
>>> array = numpy.empty((1, 1080, 1920, 3), dtype=numpy.float)
>>> float_tensor = torch.nn.functional.interpolate(
...     to_float_tensor(array),
...     size=(new_w, new_h),
...     mode="bilinear",
...     align_corners=False,
... )
>>> float_tensor.shape
torch.Size([1, 3, 720, 480])
```
Now height is ``new_w`` and width is ``new_h``.

I'll submit a pull request, but I'm not sure if that's a breaking change and if that is a concern at this stage of the project.
Maybe you should warn the detectron2 team or other people, which rely on this code.

Best Regards,
Lucas Steinmann

**Comment by wanyenlo** [comment]
Nice catch! Haoqi just submitting a change to fix it :)
