### ISSUE TITLE
The problem in conda install 

### ISSUE THREAD

**Issue by Hydrogenion** [facebookresearch/fvcore#28]
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                    

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.1=0

Your installed CUDA driver is: 10.1

Why is that?

**Comment by takatosp1** [comment]
Hi, 
Could you please kindly enough show your full log stack, thanks. Beside oof that, it would be nice if you could also share your env info.

Another way to control the env is that, you could try to run
```
git clone https://github.com/facebookresearch/fvcore
cd fvcore && pip install -e .
```
to see whether your current env is compilable.

**Comment by Hydrogenion** [comment]
> Hi,
> Could you please kindly enough show your full log stack, thanks. Beside oof that, it would be nice if you could also share your env info.
> 
> Another way to control the env is that, you could try to run
> 
> ```
> git clone https://github.com/facebookresearch/fvcore
> cd fvcore && pip install -e .
> ```
> 
> to see whether your current env is compilable.

Thanks for reply.
This is my conda info. 
BTW, how can I get full log stack?
Thanks!

     active environment : base
    active env location : /home/name/anaconda3
            shell level : 1
       user config file : /home/name/.condarc
 populated config files : /home/name/.condarc
          conda version : 4.8.2
    conda-build version : 3.10.5
         python version : 3.6.8.final.0
       virtual packages : __cuda=10.1
                          __glibc=2.23
       base environment : /home/name/anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
          package cache : /home/name/anaconda3/pkgs
                          /home/name/.conda/pkgs
       envs directories : /home/name/anaconda3/envs
                          /home/name/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.23.0 CPython/3.6.8 Linux/4.15.0-88-generic ubuntu/16.04.6 glibc/2.23
                UID:GID : 1009:1009
             netrc file : None
           offline mode : False

**Comment by takatosp1** [comment]
Thanks for using fvcore.
Seems the issue you raised tight with your specific env configuration and I was not able to reproduce it from my side.
We will push the latest fvcore to conda forge with CUDA v10.1 and feel free to try it when we have the update :P
