### ISSUE TITLE
Why convert numpy to tensor in VFlipTransform

### ISSUE THREAD

**Issue by OneDirection9** [facebookresearch/fvcore#30]
I notice that in `HFlipTransform`, you use numpy to flip images directly. But in `VFlipTransform`, you convert numpy array to torch.Tensor firstly, and the flip the array. Finally you convert to numpy again.

Why don't you use the numpy directly? Is there any performance concern?

Thanks!

**Comment by ppwwyyxx** [comment]
`torch.flip` is slow so I changed HFlipTransform to use numpy. Probably the same should apply to VFlipTransform as well, but it's not commonly used so I didn't get to test it.

**Comment by OneDirection9** [comment]
Got it. Thanks.
