### ISSUE TITLE
CropTransform leaves boxes hanging over the edge of the image

### ISSUE THREAD

**Issue by alekseynp** [facebookresearch/fvcore#33]
The CropTransform currently leaves boxes hanging over the edge of the images.
I think in most object detection pipelines I would want the boxes cropped just like the image.

```python
import numpy as np

from fvcore.transforms import CropTransform

transform = CropTransform(5, 5, 5, 5)
box = np.array([[0, 0, 10, 10]])
transform.apply_box(box)
# get: array([[-5, -5,  5,  5]])
# wanted: array([[0, 0, 5, 5]])
```

**Comment by ppwwyyxx** [comment]
It depends on what the application needs. In detectron2 they are clipped to the size of the image before entering the model.

**Comment by LovPe** [comment]
For the CropTransform along this may be a bug, because after crop, the contain outside the crop region is gone. so the annotation should clip to new contain too.
I encounter a problem when using  CropTransform and then ExtendTransform due to this problem.
My solution is to just clip coords in apply_coords:
        coords[:, 0] -= self.x0
        coords[:, 1] -= self.y0
        coords[:, 0] = np.clip(coords[:, 0], 0, self.w)
        coords[:, 1] = np.clip(coords[:, 1], 0, self.h)

**Comment by ppwwyyxx** [comment]
the box is just a box.
Whether the box is an annotation is up to the user and the application that uses the transform.

**Comment by alekseynp** [comment]
I understand now that the scope of the fvcore transforms is very limited. What I report as a problem here is actually behaviour as intended. I see that in detectron2 the cleanup is handled separately. As as naive user of deep learning computer vision transforms I expect them to handle this cleanup and I value that a lot.

I would be happy to close this issue.

Maybe the transforms could more loudly advertise their lack of cleanup so that naive users don't get tripped up. Maybe not.

**Comment by LovPe** [comment]
i see. thanks for reply.

**Comment by ppwwyyxx** [comment]
We now mention this in `Transform.apply_box`.
