### ISSUE TITLE
tensor size(0) type changes when using flop_count

### ISSUE THREAD

**Issue by ShoufaChen** [facebookresearch/fvcore#37]
When using [flop_count](https://github.com/facebookresearch/fvcore/blob/master/fvcore/nn/flop_count.py#L28), the `type(input.size(1))` is `torch.Tensor` rather than `int` when not using `flop_count`

This may cause some unexpected behavior because some operators, eg. `round` , do not support torch.tensor.

**Comment by ppwwyyxx** [comment]
`flop_count` uses jit tracing and the behavior of type change is by design of pytorch's jit tracing. 
If the model is not able to handle it, it is then not traceable, and therefore not supported by `flop_count`.
