### ISSUE TITLE
Detailed flop count for submodules

### ISSUE THREAD

**Issue by twangnh** [facebookresearch/fvcore#38]
current flop counter returns total flops of a module

https://github.com/facebookresearch/fvcore/blob/master/fvcore/nn/flop_count.py

It seems more helpful if it could calculate and returns submodule flops like:

```
module
   submodule1
   submodule2
```
I'm wondering if this will be implemented or do you have any suggestions on how to implement it or suggestions for other pkgs that perform this calculation?

**Comment by ppwwyyxx** [comment]
As far as I know, no libraries that can accurately do this exist today. But as an FYI, we're working on this feature in https://github.com/facebookresearch/fvcore/pull/53.

**Comment by ppwwyyxx** [comment]
This is done in https://github.com/facebookresearch/fvcore/blob/master/docs/flop_count.md
