### ISSUE TITLE
Problem with 'flop_count'

### ISSUE THREAD

**Issue by shen494157765** [facebookresearch/fvcore#42]
Hi, 

When I used the function 'flop_count', I got an problem.
my code is here:

```
from fvcore.nn import flop_count
from efficientnet_pytorch import EfficientNet
model = EfficientNet.from_name('efficientnet-b2')
netinput = torch.randn(1, 3, 224, 224)
final_count, skipped_ops = flop_count(model, (netinput, )) 
print(final_count)
```

And the result is 

Skipped operation aten::batch_norm 69 time(s)
Skipped operation prim::PythonOp 69 time(s)
Skipped operation aten::adaptive_avg_pool2d 24 time(s)
Skipped operation aten::sigmoid 23 time(s)
Skipped operation aten::mul 39 time(s)
Skipped operation aten::rand 16 time(s)
Skipped operation aten::add 32 time(s)
Skipped operation aten::div 16 time(s)
Skipped operation aten::dropout 1 time(s)
defaultdict(<class 'float'>, {'conv': 0.65755544, 'addmm': 0.001408})

the result  0.657B is different from the result in the efficientnet paper. https://arxiv.org/abs/1905.11946

Can you help me with this?

**Comment by ppwwyyxx** [comment]
If the results don't match, then at least one of the following three must be wrong:
1. fvcore
2. the efficientnet implementation you use
3. the efficientnet paper

We are happy to fix it if you can show us that fvcore is wrong. However checking the correctness of (2) and (3) is beyond what we can support.
