### ISSUE TITLE
flop_count requires groups=1 in conv?

### ISSUE THREAD

**Issue by amsword** [facebookresearch/fvcore#45]
based on the implementation, it does not take into account the groups if it is conv layers. So, it has to be with groups = 1?

https://github.com/facebookresearch/fvcore/blob/40229421b53b2aca1ffa974e014828a00a4bbee7/fvcore/nn/jit_handles.py#L228

**Comment by ppwwyyxx** [comment]
>  it has to be with groups = 1?

I believe that's not the case. If you found it working incorrectly for group conv, please show code to reproduce the error
