### ISSUE TITLE
** fvcore version of PathManager will be deprecated soon.** 

### ISSUE THREAD

**Issue by yangadan** [facebookresearch/fvcore#47]
** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath 

How to solve it？

**Comment by cuihaoleo** [comment]
Use `from iopath.common.file_io import PathManager` instead.

**Comment by ppwwyyxx** [comment]
If you use `fvcore.common.file_io` directly, change to `iopath.common.file_io` as suggested above.

If another library uses `fvcore.common.file_io`, updates that library to latest, or report issues to that library instead.
