### ISSUE TITLE
flop_count support more ops, such as bmm

### ISSUE THREAD

**Issue by wjfwzzc** [facebookresearch/fvcore#49]
Now `flop_count` already supports several ops with high computational costs:
https://github.com/facebookresearch/fvcore/blob/1dbd159daebf39dd1cb5911d5ab9b64418d0057e/fvcore/nn/flop_count.py#L20-L25
However with the popularity of `MultiHeadAttention`, some ops with high computational costs are not taken into consideration, such as `bmm`. Some element-wise ops can also be costly such as `mul`, `add` and `layer_norm`.
![image](https://user-images.githubusercontent.com/5126316/103261910-2fe47200-49de-11eb-8681-80eb8ea7ab7e.png)
Will `flop_count` support these ops in the future?

**Comment by ppwwyyxx** [comment]
We love to support more ops. Feel free to send PRs.
