### ISSUE TITLE
Need SoftmaxFocalLoss .

### ISSUE THREAD

**Issue by shiyongde** [facebookresearch/fvcore#5]
The detectron has SoftmaxFocalLoss , I think It's useful for some cases.

The pytorch already has the code :
https://github.com/pytorch/pytorch/blob/821b5f138a987807032a2fd908fe10a5be5439d9/modules/detectron/softmax_focal_loss_op.cu

Could you merge this ?

**Comment by ppwwyyxx** [comment]
We only implement things when they are needed by our projects.

You're welcome to implement it yourself, or contribute to fvcore.
