### ISSUE TITLE
Addition of dataclasses library not supported in python 3.6

### ISSUE THREAD

**Issue by bigswede74** [facebookresearch/fvcore#56]
The dataclasses library that was added in commit acbf982ac666fbc78428b8f5c668f03754ff4ff1 is only supported in Python 3.7. The addition of this library in commit acbf982ac666fbc78428b8f5c668f03754ff4ff1 breaks python 3.6 compatibility.

**Comment by ppwwyyxx** [comment]
thanks. you can `pip install dataclasses`
