### ISSUE TITLE
How do I cite this repo?

### ISSUE THREAD

**Issue by ekosman** [facebookresearch/fvcore#82]
Hi,

Thank you for the great tools you supply in this repo. I use the module for computing the FLOPs of a model for my project. How do you propose to cite this repo in my project report?

**Comment by ppwwyyxx** [comment]
I had cited it using the following in my paper:
```
@misc{fvcore,
  title        = {{fvcore} library},
  howpublished = {\url{https://github.com/facebookresearch/fvcore/}},
}
```

**Comment by ekosman** [comment]
@ppwwyyxx  Thanks!
